#!/usr/bin/env python3
#
# https://icalendar.readthedocs.io/en/latest/usage.html#example

import datetime
import logging
import re
import pprint
import os
import time

import click
import icalendar
import json
import pytz
import yaml

from rich.logging import RichHandler

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException


class RegalICS:
    PADDING = 25  # minutes

    THEATRES = [
        {
            "slug": "regal-bella-bottega-0904",
            "timezone": "America/Los_Angeles",
        },
    ]

    def __init__(self, verbose):
        self.verbose = verbose

        self.today = datetime.date.today()

    def get_driver(self):
        options = Options()
        options.add_argument("--window-size=1920,1080")
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        options.add_argument("--disable-blink-features=AutomationControlled")
        options.add_argument("--headless=new")

        service = webdriver.ChromeService(executable_path="/usr/bin/chromedriver")

        return webdriver.Chrome(service=service, options=options)

    def main(self):
        self.setup_logging()

        self.driver = self.get_driver()

        # Scrape data
        for theatre in self.THEATRES:
            self.handle_theatre(theatre)

        # Output .ics files
        theatre_data = []
        for theatre in self.THEATRES:
            ics = self.get_ics(theatre)

            with open(f"ics/{theatre['slug']}.ics", "w") as f:
                f.write(ics)

            theatre_data.append(theatre["_main"]["theatreData"]["data"])

        # Write theatre metadata
        with open(f"_data/theatres.yaml", "w") as f:
            f.write(yaml.dump(theatre_data))

        self.driver.quit()

    def get_main_theatre_page(self, theatre):
        url = "https://www.regmovies.com/theatres/{}".format(
            theatre["slug"],
        )

        while True:
            self.driver.get(url)

            try:
                elem = self.driver.find_element(
                    By.XPATH, "//script[@id='__NEXT_DATA__']"
                )
                break
            except NoSuchElementException:
                logging.warning(
                    f"Could not find <script> element accessing {url}, trying again…"
                )
                time.sleep(10)

        data = json.loads(elem.get_attribute("textContent"))

        return data["props"]["pageProps"]

    def api(self, theatre, date):
        theatre_number = theatre["slug"].split("-")[-1]
        date_fmt = date.strftime("%m-%d-%Y")

        url = f"https://www.regmovies.com/api/getShowtimes?theatres={theatre_number}&date={date_fmt}&hoCode=&ignoreCache=false&moviesOnly=false"

        while True:
            self.driver.get(url)

            try:
                elem = self.driver.find_element(By.XPATH, "//pre")
                break
            except NoSuchElementException:
                logging.warning(
                    f"Could not find <pre> element accessing {url}, trying again …"
                )
                time.sleep(5)

        return json.loads(elem.get_attribute("textContent"))

    def handle_theatre(self, theatre):
        # Get the data embedded on the main page
        main = self.get_main_theatre_page(theatre)

        # Save the theatre data
        theatre["_main"] = main

        # Use datesWithShows from first day to find dates with shows
        dates = []
        for x in main["datesWithShows"]:
            date = datetime.date(int(x[:4]), int(x[5:7]), int(x[8:10]))
            dates.append(date)

        fn = logging.warning if len(dates) == 0 else logging.debug
        fn(f"Found {len(dates)} days we need to scrape for {theatre['slug']}")

        showtimes = []
        with click.progressbar(dates) as dates:
            for date in dates:
                showtimes.append((date, self.api(theatre, date)))

        theatre["_showtimes"] = showtimes

    def get_ics(self, theatre):
        base_url = f"https://www.regmovies.com/theatres/{theatre['slug']}/"

        main = theatre["_main"]
        theatre_data = main["theatreData"]["data"][0]

        movies = {x["MasterMovieCode"]: x for x in main["movies"]}
        logging.debug(f"We know about {len(movies)} movies")

        address = "{}, {}, {} {}".format(
            theatre_data["address"],
            theatre_data["city"],
            theatre_data["state"],
            theatre_data["postal_code"],
        )

        timezone = pytz.timezone(theatre["timezone"])

        cal = icalendar.Calendar()
        cal.add("prodid", "-//icalendar//mxm.dk//")
        cal.add("version", "2.0")
        cal.add("name", f"Cinema 🇺🇸 {theatre_data['name']}")
        cal.add("x-wr-calname", f"Cinema 🇺🇸 {theatre_data['name']}")
        cal.add("last-modified", datetime.datetime.now(datetime.UTC))

        num_events_venue = 0
        for date, showtimes in theatre["_showtimes"]:
            try:
                if not showtimes["shows"]:
                    continue
            except KeyError:
                continue

            for film in showtimes["shows"][0]["Film"]:
                title = self.tidy_title(film["Title"])

                if title.endswith(" (Sensory)"):
                    continue

                if film["MasterMovieCode"] not in movies:
                    logging.warning(f"No metadata for movie {film['MasterMovieCode']} {film}")
                    continue

                movie = movies[film["MasterMovieCode"]]

                duration = movie["Duration"]
                hours, minutes = divmod(duration, 60)

                for x in film["Performances"]:
                    event = icalendar.Event()

                    event.add("uid", x["PerformanceId"])
                    event.add("summary", title)
                    event.add(
                        "location", "{}, {}".format(theatre_data["name"], address)
                    )

                    # UnixTime is actually offset by timezone so we need to convert it back
                    start = timezone.localize(
                        datetime.datetime.fromtimestamp(
                            x["UnixTime"] / 1000,
                        )
                    )
                    start -= datetime.timedelta(
                        seconds=start.utcoffset().total_seconds()
                    )

                    estimated_start = start + datetime.timedelta(
                        minutes=self.PADDING,
                    )
                    end = estimated_start + datetime.timedelta(
                        minutes=self.round_to_nearest(duration, 5),
                    )
                    event.add("dtstamp", start)
                    event.add("dtstart", start)
                    event.add("dtend", end)

                    description = [
                        f"Duration: {duration} mins ({hours}h{minutes:02d}m)",
                        "Screen {}".format(x["Auditorium"]),
                        "",
                        movie["Description"],
                        "",
                        f"Estimated start: {estimated_start.hour}:{estimated_start.minute:02d}",
                    ]

                    event.add("description", "\n".join(description))

                    cal.add_component(event)

                    num_events_venue += 1

        fn = logging.warning if num_events_venue == 0 else logging.debug
        fn(f"Found {num_events_venue} total events for {theatre_data['name']}")

        return cal.to_ical().decode("utf-8")

    def tidy_title(self, val):
        val = re.sub(
            r"\s+\((?:Hindi|Telugu|Malayalam)\)$", "", val, flags=re.IGNORECASE
        )

        val = re.sub(r"Open Cap/Eng Sub", "Subbed", val, flags=re.IGNORECASE)

        val = re.sub(r"\s+-\s+Early Access$", "", val, flags=re.IGNORECASE)
        val = re.sub(r"^SMX\d+:\s+", "", val, flags=re.IGNORECASE)
        val = re.sub(r"\s+\d+..\s+Anniversary$", "", val, flags=re.IGNORECASE)

        val = re.sub(r"\s+-\s+Ghibli\s+\d+$", "", val, flags=re.IGNORECASE)
        val = re.sub(r"Anniv\.?$", "Anniversary", val, flags=re.IGNORECASE)

        return val

    def round_to_nearest(self, val, nearest_to):
        return (val + (nearest_to - 1)) // nearest_to * nearest_to

    def setup_logging(self):
        level = logging.DEBUG if self.verbose else logging.INFO
        logging.basicConfig(
            level=level, format="%(message)s", datefmt="[%X]", handlers=[RichHandler()]
        )


@click.command()
@click.option("--verbose", is_flag=True, default=False, help="Verbose.")
def main(verbose):
    RegalICS(verbose).main()


if __name__ == "__main__":
    main()
